# Generated by Django 4.1.3 on 2022-11-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.IntegerField(primary_key=True, serialize=False)),
                ('Cargo', models.CharField(max_length=60, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=60, verbose_name='Teléfono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Sueldo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo')),
            ],
        ),
    ]
