# Generated by Django 4.1.3 on 2022-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50, verbose_name='Nombre proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='proyecto',
            field=models.ManyToManyField(related_name='proyecto_empleado', to='empleados.proyecto'),
        ),
    ]
